[package]
name = "socks5_frontend"
version = "0.1.0"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "~1"

[dev-dependencies]
simple-server = "~0"
portpicker = "~0"
reqwest = {features = ["socks"], version = "~0"}